name: npm CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]


jobs:

  build-and-test:
    runs-on: ubuntu-20.04
    name: Install dependencies
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm config set legacy-peer-deps true
          npm ci
    name: Run unit tests
        - run: npm run test:unit
    name: Build
        - run: npm run build --if-present
          
