name: npm CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - name: npm install, build and unit test
      - run: |
          npm install
          npm run build --if-present
          npm run test:unit
